### ISSUE TITLE
Connexion BDD

### ISSUE THREAD

**Issue by Som4t** [Som4t/CreationPhrase#1]
Veuillez avoir l'obligeance de modifier vos fichier afin de separer les identifiants de connexion a la BDD ainsi que mot de passe dans un nouveau fichier que je me permettrai de gitignorer

**Comment by Antoine645213** [comment]
Vu

**Comment by Som4t** [comment]
c'en est où ? le Client est assez méticuleux sur les délais

**Comment by Antoine645213** [comment]
Impossibilité, l'équipe est en congé malheureusement

**Comment by Som4t** [comment]
Les congés ont été refusé étant donner que vous êtes le seul dévellopeur de l'équipe

**Comment by Som4t** [comment]
Vous serez renvoyer pour abandon de poste

**Comment by Antoine645213** [comment]
Vous n'êtes point supérieur à moi, vous appartenez à un autre secteur de l'entreprise.

**Comment by Antoine645213** [comment]
Correction effectuée.
